### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by thundrchickn** [BSData/whfb#123]
hello.  can i get added

**Comment by Maetco** [comment]
Could someone with appropriate rights add this guy/gal?

**Comment by amis92** [comment]
Oh hey, I have no idea how I missed it, I check for requests once upon a time... @thundrchickn I'm adding you, please accept the invitation!

**Comment by amis92** [comment]
@thundrchickn You have one week to accept the invitation, after that I'll delete the invitation and you'll have to re-apply.

I hope you understand - I'm doing organisation cleanup :)
