### ISSUE TITLE
High Elves - 8thBRB_8thAB.cat - Rooster view

### ISSUE THREAD

**Issue by AncestralD** [BSData/whfb#124]
Something has happened.the rooster view for high elves. it has lost the refences, like armor save and the little description of items below the unit stats etc.

**Comment by Maetco** [comment]
I don't see anything wrong in the View Roster. It shows the information I select on the left. Are you sure it's not just the new feature where you have more control over what is shown?

**Comment by AncestralD** [comment]
i see. well, when i made a rooster before it was missing. now its not.. :) so all is good and done.. is it possible to update an old rooster, to the updated one, or do i have to remake the old rooster?
