### ISSUE TITLE
[Join Request Please]

### ISSUE THREAD

**Issue by Cruentus-Tigris** [BSData/whfb#131]
Hello,

i would like to join and help update the skaven profile and help out else where if needed

Cheers Cru

**Comment by Maetco** [comment]
Could someone with appropriate rights add this guy/gal?

**Comment by amis92** [comment]
Oh hey, I have no idea how I missed it, I check for requests once upon a time... @Cruentus-Tigris  I'm adding you, please accept the invitation!
