### ISSUE TITLE
[Join Request] Warhammer Fantasy Battles - Wood Elves

### ISSUE THREAD

**Issue by taalas** [BSData/whfb#188]
Hi!

I recently started back into the hobby and am currently playing my Wood Elves in 8th. While printing army lists I noticed that a couple of profiles are missing from the Wood Elves data file. If you are interested I would be happy to complete that file.

Best regards
Markus

**Comment by amis92** [comment]
Of course, thanks for joining. Please don't forget to accept your invitation. Welcome aboard!
