### ISSUE TITLE
Plans for Age of Sigmar

### ISSUE THREAD

**Issue by taalas** [BSData/whfb#190]
Hi!

With the Warscrolls for Age of Sigmar available today, is there any plan on how or of to tackle this for the whfb repository? Has anybody starting planning anything on this yet?

**Comment by amis92** [comment]
Well I think a new repository is due, this is completely new game in terms of rules. Here you go: https://github.com/BSData/warhammer-age-of-sigmar

When someone comes up with files, please put them in that repo.

**Comment by taalas** [comment]
Thanks Amadeusz!

I guess having a seperate repository might be a good idea. Now to come up with a plan on how to tackle the organization of the new system but I will ask that over there...

**Comment by amis92** [comment]
(reference to actual issue on AoS repo: https://github.com/BSData/warhammer-age-of-sigmar/issues/1)
