### ISSUE TITLE
7th edition files

### ISSUE THREAD

**Issue by Neisseria337** [BSData/whfb#191]
Hi everyone, I apologise if this is not the correct way to go about this request, but I figured it would be the easiest way to reach the most people. Does anyone still have the BS files for 7th edition WHFB, particularly the core system and VC/Skaven lists if not everything else? If so, could you please point me in the right direction to download them? Since AoS, my gaming group is resurrecting 7th, so I would like to have the older version on my app. Thanks very much!

**Comment by DurzoBlintDeluxe** [comment]
Skaven 7th edition are now useable. Please report issues, if you find them. I'll try to fix them in time.
