### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by adriancollier** [BSData/whfb#205]
Hi there, just paid for battlescribe to notice that the Dark Elves stats aren't there. I have the 8th edition stats and the synax is clear in the source code so I'm pretty sure I can update this given some time.

**Comment by amis92** [comment]
You have to notice we are not affiliated with BattleScribe. Data repository is community-driven and you paying for that product (we all love BTW) doesn't really matter for us :) Just to be sure we both understand each other.

Well, of course that would be great! We welcome you very happily. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide). Cheers!

**Comment by adriancollier** [comment]
Thanks! I mainly mentioned the purchase to let you know of my motivation :smile:

I'll take a branch shortly and get cracking!
