### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by BogdanSlaschov** [BSData/whfb#210]

**Comment by amis92** [comment]
Hello, @BogdanSlaschov . Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
Amis
