### ISSUE TITLE
[Anon] Bug report: Tomb Kings - 8thBRB_8thAB.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#211]
**File:** Tomb Kings - 8thBRB_8thAB.catz

**BattleScribe version:** 2.00.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** After I updated my BattleScribe and it deleted all my data files and won't install the warhammer fantasy data files when I try to get them back. Is this because it's not supported by the new version of BattleScribe.

**Comment by WarbossDoozer** [comment]
warhammer fantasy data appears working correctly under version 2.0. on both android and windows platforms.

**Comment by Kithan87** [comment]
Not reproducible.
