### ISSUE TITLE
Validation errors for most armies

### ISSUE THREAD

**Issue by adriancollier** [BSData/whfb#215]
I think something's up with the total validators - there's an error in most of the army lists with the latest version:
![screen shot 2016-12-06 at 10 12 12](https://cloud.githubusercontent.com/assets/1426234/20919534/8c421bd0-bb9c-11e6-8317-0deca7dcc156.png)

It shouldn't be too difficult to fix though

**Comment by Kithan87** [comment]
Unable to reproduce with BS v2.03.12
