### ISSUE TITLE
Bug report: Skaven - 8thBRB_7thAB.catz - Plague Priest Level 2 not available

### ISSUE THREAD

**Issue by misanuk** [BSData/whfb#216]
Game: WHFB

Rules: 8th Edition (standard)

Army: Skaven

Character: Plague Priest

Issue: Wizard Level 2 not available as an option. Should be available for +35 pts.

**Comment by Kithan87** [comment]
No longer reproducible, already been fixed in v19 of the army book and BS v2.03.12
