### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by stancranford** [BSData/whfb#219]
Hi, I have a complete repository of data files for Warhammer Fantasy Battle 7th edition and am working on files for the 5th edition, and I would like to publish them.

**Comment by amis92** [comment]
Hello, @stancranford. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!

PS About that 5th ed, I'd suggest packing it as .bsr file and upload as an attachement to some release. You can also ask further :D
