### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by bosefalk** [BSData/whfb#228]
Hey, I want to join to help fix a number of small issues I've noticed, in particular update the wood elf army

**Comment by amis92** [comment]
Hello, @bosefalk. Please accept the invitation in the email or on the https://github.com/BSData/whfb/invitations. Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
