### ISSUE TITLE
Wood Elf incomplete entries

### ISSUE THREAD

**Issue by bosefalk** [BSData/whfb#229]
Wood Elves have a number of incomplete entries, profiles, magic weapons etc. I'm planning to work on completing this over the near future - please add a comment with anything else missing. I'm not planning to do all special rules for the named characters, just their basic profiles.

Unit profiles:
	All Lord choices
	Branchwraith
	Drycha
	Naestra and Arahan
	Glade Riders
	Tree Kin
	Great Eagle
	Treeman
	All Mounts

All lords and heroes are missing unit type
All Magic Items (incl arrows) are missing descriptions & stats
All mundane weapons are missing stats

Special Rules missing:
	Glade Lord: all
	Spellweaver: all
	Ancient Treeman: all
	Glade Captain: Arrow of Kurnous
	Branchwraith: all, incl Magic user
	Mounts: all
	Shadowdancer: Two hand weapons
	Eternal Guards: Spears
	Glade Guards: Longbows
	Glade Riders: everything, incl weapons
	Deepwood Scouts: Longbows, Forest Stalker instead of Forest Spirit
	Sisters of the Thorn: Steed of Isha, ASF (riders only), Poisoned Attacks description
	Treekin: everything
	Wardancer: weapons (two & spear)
	Warhawks Riders: Add mundane weapons (spear & longbow), ASF riders only
	Wild Rider: Type, weapons, ASF rider only, Devastating Charge riders only, shields bug
	Wildwood Rangers: Type, great weapons, wrong armour save
	Great Eagle: everything
	Treeman: everything, incl Strangleroot
	Waywatchers: Two hand weapons, longbow

**Comment by Cupropituvanso** [comment]
I am also working and playing on wood elves ... and the things you write that are missing are very much implemented and uploaded on github!!

Mayve they are not releaded??

**Comment by Cupropituvanso** [comment]
I think it would be good if we speak around directly before you start working :) Maybe on gitter?

**Comment by bosefalk** [comment]
Thanks - i dropped you a msg on gitter and will be online later tonight. There is an outstanding pull request https://github.com/BSData/whfb/pull/201 but the .cat file there appears to be corrupted

**Comment by Cupropituvanso** [comment]
After chat it is clear *g*

I was mobile and got the mail with the info, that the file is corrupt and units are missing .
I have not seen, that the issue was made in the WHFB ... I am working on AoS :)

Now I have disabled the notifications for WHFB :) Sorry *g*
