### ISSUE TITLE
[Join Request] WHFB 7th ed

### ISSUE THREAD

**Issue by DurzoBlintDeluxe** [BSData/whfb#270]
Hi everyone,

as stated in [issue 72](https://github.com/BSData/catalogue-development/issues/72 ) I want to contribute some data files for the 7th edition. It would be great, if I can join and maybe create a new repo for this BS.

**Comment by amis92** [comment]
As stated in the linked issue, we don't create new repositories for different editions. There's no problem however to maintain two editions in parallel in the same repo. :)

**Comment by amis92** [comment]
And it seems there's already/still files for 7th.

**Comment by amis92** [comment]
Hello, @DurzoBlintDeluxe. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!

PS. @OftKilted please assist him in getting started in this repo.

[invitation]: https://github.com/BSData/whfb/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

**Comment by OftKilted** [comment]
@DurzoBlintDeluxe drop on by Discord and we can get you started.

**Comment by DurzoBlintDeluxe** [comment]
Thank you.
I recently joined Discord. I'll try to find you there. 
See ya
