### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by mikewoe** [BSData/whfb#288]
Want to take part in fixing some issues with FB 8th edition

Have some problems with dwarfs, for example, with runes.

**Comment by amis92** [comment]
I'd suggest starting with some Pull Requests, but it's up to @OftKilted.

**Comment by OftKilted** [comment]
@mikewoe Hey Mikewoe! I see your request to join is your first item on Github! Welcome to Github! Can I have you submit a bug report for the Dwarf issue, and a pull request with your proposed fixes? Are you on the Battlescribe Discord yet?

**Comment by mikewoe** [comment]
@OftKilted hi, friend!

Nope, this is not my first item on github - i have ~ 20 private repos and use this account from 2016. As i see in #287 were closed most issues with runes.

Need to check new version, to make opinion about fixes. I'm new in Warhammer FB, so i can checking something only on my main race in game for now.

> Are you on the Battlescribe Discord yet?
Yes

**Comment by OftKilted** [comment]
> > Are you on the Battlescribe Discord yet?
> 
> Yes

Cool! Drop me an IM, and feel free to submit a pull request to the WHFB for any issues you're working on. And we can see about adding you as a contributor.

**Comment by amis92** [comment]
This issue is stale and most probably no longer useful. If you want to continue this discussion, please reopen this issue or create a new one.

Thank you.
