### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by stancranford** [BSData/whfb#292]
Hi, I have a just finished writing a complete set of files for all armies in Warhammer Fantasy Battle 7th Edition, and am looking to upload them for use.
Also, I have never used GitHub before so I may need some handholding to upload them!

Thanks,

**Comment by amis92** [comment]
I'll just link you to https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

Other than that, @OftKilted would you help our new collaborator out? :)

**Comment by OftKilted** [comment]
Is this a rebuild of the current 7e files? A brand new implementation?

**Comment by stancranford** [comment]
Hi,

Yeah, it's a scratch built set of files for all the playable armies in 7th
Ed. How would I go about uploading them?

**Comment by amis92** [comment]
@stancranford have you seen the current 7th ed files? How do they compare?

**Comment by stancranford** [comment]
I looked at them, but didn't think they worked that well, so I made my own
from scratch.

**Comment by OftKilted** [comment]
@stancranford Do you have a repo for them currently? Are you using the current GST for WHFB? (a different GST?)

Can you drop into the Discord?

**Comment by amis92** [comment]
This issue is stale and most probably no longer useful. If you want to continue this discussion, please reopen this issue or create a new one.

Thank you.
