### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by NiKourou** [BSData/whfb#295]
Hi! I am new at programming but I want to learn more and contribute to my favorite hobbie, warhammer fantasy. I dont know what you guys need, but I know only java. I hope I can help.

If you want to know more about me, you can freely ask.

Nikos

**Comment by OftKilted** [comment]
@nonfactor Come on and join us over on the discord so we can chat about what you're looking to help with :) https://discord.gg/KqPVhds 
We work on catalog coding using Battlescribe. Understanding programming logic is helpful, knowing how to program, not required.

**Comment by amis92** [comment]
This issue is stale and most probably no longer useful. If you want to continue this discussion, please reopen this issue or create a new one.

Thank you.
