### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Tilioch** [BSData/whfb#297]
Hi
I'd like to join in and create some files for 4th and perhaps also 5th edition WHFB

**Comment by OftKilted** [comment]
@Tilioch Drop into the Discord and join the discussions. 
Do you have a repo where you've configured your current files so we could look at your examples?

**Comment by Tilioch** [comment]
Joined the channel on discord now under the name Tilioch.
I havent set up a repro for my whfb files so far, I but here I manage the Flames of War one. I guess I could set up a private repro with the files I have so far it you need me too

**Comment by OftKilted** [comment]
> Joined the channel on discord now under the name Tilioch.
> I havent set up a repro for my whfb files so far, I but here I manage the Flames of War one. I guess I could set up a private repro with the files I have so far it you need me too

Awesome, feel free to visit in the whfb-data discussion on the discord.

**Comment by OftKilted** [comment]
@Tilioch Sent invite after basic code review of personal code repo. Closing issue.
