### ISSUE TITLE
Command groups 4th Ed

### ISSUE THREAD

**Issue by arraboy1** [BSData/whfb#301]
The points cost for adding unit champions, musicians and standard bearers assumes you what to add new members to the regiment. Can the points cost instead be for just the cost of upgrading and existing model? Otherwise its impossible to have a minimum sized unit with a command group.

**Comment by Tilioch** [comment]
I have it on my ToDo list and will prioritize it

**Comment by Tilioch** [comment]
The places where this is an issue has been fixed, a champion however is a character and will be an additional model in a unit, not a upgrade for one of the members in the unit.

**Comment by Tilioch** [comment]
After further reading in a few different army books, there is some that say that the champion may take the place for from a normal warrior, so will change this in all files to give them all the same structure
