### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by salmonc97** [BSData/whfb#306]
I'd like to fill in some of the 7th edition things, especially the alternative and smaller army lists from white dwarfs and campaign books throughout the 6tg and 7th edition era. The gnoblar horde, army of the lichemaster, things like that.

**Comment by OftKilted** [comment]
@salmonc97 Do you have any work you've done or proposed commits?

**Comment by amis92** [comment]
@salmonc97 if you happen to respond, feel free to reopen this issue.
