### ISSUE TITLE
[Anon] Bug report: Warhammer_Fantasy_4th_ed.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#310]
**File:** Warhammer_Fantasy_4th_ed.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Black Amulet is missing from magic items.

50pts

Negates any wound on a 4+. In hand to hand combat any wound saved by the amulet is rebounded against the foe, no saving throw allowed, not even for magic armour.

**Comment by Tilioch** [comment]
Item exists in Devices of Protection, closing
