### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by firebirdie** [BSData/whfb#321]
hi !

i think im in the right place (if not some assistance would be welcome XD, the tutorial video is like 8 years old and prob outdated )
it's bin a while since anybody updated the WHFB rosters and there are some bugs that still need to be fixed
i fixed a few in my own data editor and would like to share them by updating the existing files 
i also had a look in the bug reports and i'm sure i can fix minor issues here and there that the people have reported over the last 2 years

one of these bugs i reported to the author directly a few months ago and he said he would have a look at it but then never did 
so i figured il do it myself and hopefully can share with future whfb players

thnx in advance

jc phoenix

**Comment by OftKilted** [comment]
Please submit your proposed corrections as pull requests and document them with references to the associated ticket number.

**Comment by firebirdie** [comment]
ah i thought only contributors were able to make pull requests , regardless , if you have 10 mins time , could you show/explain it to me once  @OftKilted

**Comment by DrTobogganMD** [comment]
Per @OftKilted, user will submit changes via PR
